### ISSUE TITLE
documentation for @class needs format fix

### ISSUE THREAD

**Issue by lmccart** [therewasaguy/p5.sound#28]
When the autodoc generator is run, some of the classes for p5.sound are getting lost because of the yuidocs format in the source.

This class looks right:
https://github.com/therewasaguy/p5.sound/blob/master/lib/p5.sound.js#L1684

But ones like these are breaking:
https://github.com/therewasaguy/p5.sound/blob/master/lib/p5.sound.js#L2046

The description can be moved up above, just before the @class declaration. Then @class can be followed by the name of the class.

**Comment by therewasaguy** [comment]
It's actually good that those classes are not showing up in the reference. They're from a few Tone.js modules that have been swapped in to help power signal math and metronome, similar to how p5.js uses reqwest. So that documentation is meant for the Tone reference, not p5. It also includes some stuff that is not being used by p5.sound, and I should try to trim that... at first, I did that manually and removed all the unnecessary comments—all it really needs is a line for attribution. I'm looking for a way to automate this as part of the build script. Do you have any suggestions for how to only remove comments from certain modules?

When you say that these are breaking, do you mean they're causing other problems? If so lemme know and I'll make this more of a priority!

**Comment by lmccart** [comment]
ahh I see, ok!

![screen shot 2015-01-30 at 8 25 23 am](https://cloud.githubusercontent.com/assets/191056/5976247/93b2c20a-a859-11e4-8d40-25c998ebb04f.png)

it looks like it's trying to generate class pages and put these categories into the docs even though you intend for them to be hidden. could we just remove the `@class` token from these ones?

as for ignoring modules, looks like you could use add an `ignorePaths` item in the gruntfile to tell yuidocs to ignore a whole file (http://yui.github.io/yuidoc/args/index.html) or I think the `@private` token should skip individual entries (http://yui.github.io/yuidoc/syntax/index.html). I haven't tested either of these..

**Comment by therewasaguy** [comment]
I figured out how to remove comments only from npm modules and will send updated pull requests to p5.js and p5js.org. The yuidocs solution may come in handy in the future, but for now we're generating docs from the single p5.sound.js file by running yuidocs from p5.js.
